const CACHE = 'trainer-v27';

const CORE = [
  './',
  './index.html',
  './manifest.json',
  './sw.js',
  './css/base.css',
  './css/exercises.css',
  './css/plans.css',
  './css/modals.css',
  './css/bodyweight.css',
  './css/nutrition.css',
  './css/summary.css',
  './css/exerciselog.css',
  './css/auth.css',
  './js/app.js',
  './js/auth.js',
  './js/state.js',
  './js/store.js',
  './js/cloud.js',
  './js/storage.js',
  './js/firebase-config.js',
  './js/utils.js',
  './js/navigation.js',
  './js/exercises.js',
  './js/plans.js',
  './js/bodyweight.js',
  './js/nutrition.js',
  './js/history.js',
  './js/prs.js',
  './js/summary.js',
  './js/exerciselog.js',
  './js/export.js',
  './data/exercises.js',
  './data/ingredients.js',
];

const ASSETS = [
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/sclae.png',
  './assets/icons/youtube-logo-icon.png',
  './assets/muscles/abductors.png',
  './assets/muscles/abs.png',
  './assets/muscles/adductors.png',
  './assets/muscles/all.png',
  './assets/muscles/all_lower.png',
  './assets/muscles/all_upper.png',
  './assets/muscles/back.png',
  './assets/muscles/back_lower.png',
  './assets/muscles/back_upper.png',
  './assets/muscles/background.png',
  './assets/muscles/baseImage.png',
  './assets/muscles/baseImage_transparent.png',
  './assets/muscles/biceps.png',
  './assets/muscles/calfs.png',
  './assets/muscles/chest.png',
  './assets/muscles/core.png',
  './assets/muscles/core_lower.png',
  './assets/muscles/core_side.png',
  './assets/muscles/core_upper.png',
  './assets/muscles/forearm.png',
  './assets/muscles/forearms.png',
  './assets/muscles/gluteus.png',
  './assets/muscles/hamstring.png',
  './assets/muscles/hands.png',
  './assets/muscles/latissimus.png',
  './assets/muscles/legs.png',
  './assets/muscles/neck.png',
  './assets/muscles/quadriceps.png',
  './assets/muscles/shoulders.png',
  './assets/muscles/shoulders_back.png',
  './assets/muscles/shoulders_front.png',
  './assets/muscles/triceps.png',
  './assets/foods/dairy/almond-milk.jpg',
  './assets/foods/dairy/butter.jpg',
  './assets/foods/dairy/cheddar-cheese.jpg',
  './assets/foods/dairy/coconut-milk.jpg',
  './assets/foods/dairy/cottage-cheese.jpg',
  './assets/foods/dairy/cream-cheese.jpg',
  './assets/foods/dairy/egg-whites.jpg',
  './assets/foods/dairy/eggs.jpg',
  './assets/foods/dairy/feta-cheese.jpg',
  './assets/foods/dairy/greek-yogurt.jpg',
  './assets/foods/dairy/mozzarella.jpg',
  './assets/foods/dairy/oat-milk.jpg',
  './assets/foods/dairy/parmesan.jpg',
  './assets/foods/dairy/ricotta.jpg',
  './assets/foods/dairy/skim-milk.jpg',
  './assets/foods/dairy/whole-milk.jpg',
  './assets/foods/fruits/apple.jpg',
  './assets/foods/fruits/avocado.jpg',
  './assets/foods/fruits/banana.jpg',
  './assets/foods/fruits/blueberries.jpg',
  './assets/foods/fruits/dates.jpg',
  './assets/foods/fruits/grapes.jpg',
  './assets/foods/fruits/mango.jpg',
  './assets/foods/fruits/orange.jpg',
  './assets/foods/fruits/pineapple.jpg',
  './assets/foods/fruits/strawberries.jpg',
  './assets/foods/fruits/watermelon.jpg',
  './assets/foods/grains/bagel.jpg',
  './assets/foods/grains/brown-rice.jpg',
  './assets/foods/grains/corn-tortilla.jpg',
  './assets/foods/grains/cornflakes.jpg',
  './assets/foods/grains/couscous.jpg',
  './assets/foods/grains/flour-tortilla.jpg',
  './assets/foods/grains/granola.jpg',
  './assets/foods/grains/oats.jpg',
  './assets/foods/grains/pasta.jpg',
  './assets/foods/grains/pita-bread.jpg',
  './assets/foods/grains/popcorn.jpg',
  './assets/foods/grains/quinoa.jpg',
  './assets/foods/grains/white-bread.jpg',
  './assets/foods/grains/white-rice.jpg',
  './assets/foods/grains/whole-wheat-bread.jpg',
  './assets/foods/legumes/black-beans.jpg',
  './assets/foods/legumes/chickpeas.jpg',
  './assets/foods/legumes/edamame.jpg',
  './assets/foods/legumes/green-peas.jpg',
  './assets/foods/legumes/hummus.jpg',
  './assets/foods/legumes/kidney-beans.jpg',
  './assets/foods/legumes/lentils.jpg',
  './assets/foods/legumes/tofu.jpg',
  './assets/foods/meat/beef-steak.jpg',
  './assets/foods/meat/chicken-breast.jpg',
  './assets/foods/meat/chicken-thigh.jpg',
  './assets/foods/meat/ground-beef.jpg',
  './assets/foods/meat/turkey-breast.jpg',
  './assets/foods/nuts-and-seeds/almond-butter.jpg',
  './assets/foods/nuts-and-seeds/almonds.jpg',
  './assets/foods/nuts-and-seeds/cashews.jpg',
  './assets/foods/nuts-and-seeds/chia-seeds.jpg',
  './assets/foods/nuts-and-seeds/flax-seeds.jpg',
  './assets/foods/nuts-and-seeds/macadamia-nuts.jpg',
  './assets/foods/nuts-and-seeds/peanut-butter.jpg',
  './assets/foods/nuts-and-seeds/peanuts.jpg',
  './assets/foods/nuts-and-seeds/pistachios.jpg',
  './assets/foods/nuts-and-seeds/pumpkin-seeds.jpg',
  './assets/foods/nuts-and-seeds/sesame-seeds.jpg',
  './assets/foods/nuts-and-seeds/sunflower-seeds.jpg',
  './assets/foods/nuts-and-seeds/tahini.jpg',
  './assets/foods/nuts-and-seeds/walnuts.jpg',
  './assets/foods/oils-and-condiments/coconut-oil.jpg',
  './assets/foods/oils-and-condiments/honey.jpg',
  './assets/foods/oils-and-condiments/maple-syrup.jpg',
  './assets/foods/oils-and-condiments/olive-oil.jpg',
  './assets/foods/oils-and-condiments/soy-sauce.jpg',
  './assets/foods/saved-meals/Egg-Savory-Oats.webp',
  './assets/foods/saved-meals/Spicy-Salmon-Sweet-Potato.jpg',
  './assets/foods/saved-meals/teriyaki-chicken-rice-bowl.jpg',
  './assets/foods/seafood/salmon.jpg',
  './assets/foods/seafood/sardines.jpg',
  './assets/foods/seafood/tilapia.jpg',
  './assets/foods/seafood/tuna.jpg',
  './assets/foods/snacks/dark-chocolate.jpg',
  './assets/foods/supplements/whey-protein.jpg',
  './assets/foods/vegetables/asparagus.jpg',
  './assets/foods/vegetables/bell-pepper.jpg',
  './assets/foods/vegetables/broccoli.jpg',
  './assets/foods/vegetables/cabbage.jpg',
  './assets/foods/vegetables/carrot.jpg',
  './assets/foods/vegetables/cauliflower.jpg',
  './assets/foods/vegetables/celery.jpg',
  './assets/foods/vegetables/corn.jpg',
  './assets/foods/vegetables/cucumber.jpg',
  './assets/foods/vegetables/eggplant.jpg',
  './assets/foods/vegetables/garlic.jpg',
  './assets/foods/vegetables/green-beans.jpg',
  './assets/foods/vegetables/kale.jpg',
  './assets/foods/vegetables/lettuce.jpg',
  './assets/foods/vegetables/mushrooms.jpg',
  './assets/foods/vegetables/onion.jpg',
  './assets/foods/vegetables/potato.jpg',
  './assets/foods/vegetables/spinach.jpg',
  './assets/foods/vegetables/sweet-potato.jpg',
  './assets/foods/vegetables/tomato.jpg',
  './assets/foods/vegetables/zucchini.jpg',
];

// Pre-cache core files on install, then cache assets in the background
self.addEventListener('install', e => {
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(CORE)).then(() =>
      caches.open(CACHE).then(c => c.addAll(ASSETS).catch(() => {}))
    )
  );
});

// Take control immediately & clean old caches
self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => clients.claim())
  );
});

// Network first — always get fresh code, fall back to cache if offline
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET' || !e.request.url.startsWith('http')) return;
  e.respondWith(
    fetch(e.request)
      .then(res => {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
        return res;
      })
      .catch(() => caches.match(e.request))
  );
});
