const CACHE = 'trainer-v131';

const CORE = [
  './',
  './index.html',
  './manifest.json',
  './sw.js',
  './css/base.css',
  './css/exercises.css',
  './css/plans.css',
  './css/modals.css',
  './css/bodyweight.css',
  './css/nutrition.css',
  './css/summary.css',
  './css/exerciselog.css',
  './css/auth.css',
  './js/app.js',
  './js/auth.js',
  './js/state.js',
  './js/store.js',
  './js/cloud.js',
  './js/storage.js',
  './js/firebase-config.js',
  './js/utils.js',
  './js/navigation.js',
  './js/exercises.js',
  './js/plans.js',
  './js/bodyweight.js',
  './js/nutrition.js',
  './js/history.js',
  './js/prs.js',
  './js/summary.js',
  './js/exerciselog.js',
  './js/export.js',
  './js/gallery.js',
  './js/musclebalance.js',
  './css/musclebalance.css',
  './js/session.js',
  './css/session.css',
  './js/ai.js',
  './assets/fonts/bootstrap-icons.css',
  './assets/fonts/fonts/bootstrap-icons.woff2',
  './assets/fonts/fonts/bootstrap-icons.woff',
  './data/exercises.js',
  './data/ingredients.js',
];

const ASSETS = [
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/banner.png',
  './assets/icons/sclae.png',
  './assets/icons/meal.jpg',
  './assets/icons/youtube-logo-icon.png',
  './assets/muscles/abductors.png',
  './assets/muscles/abs.png',
  './assets/muscles/adductors.png',
  './assets/muscles/all.png',
  './assets/muscles/all_lower.png',
  './assets/muscles/all_upper.png',
  './assets/muscles/back.png',
  './assets/muscles/back_lower.png',
  './assets/muscles/back_upper.png',
  './assets/muscles/background.png',
  './assets/muscles/baseImage.png',
  './assets/muscles/baseImage_transparent.png',
  './assets/muscles/biceps.png',
  './assets/muscles/calfs.png',
  './assets/muscles/chest.png',
  './assets/muscles/core.png',
  './assets/muscles/core_lower.png',
  './assets/muscles/core_side.png',
  './assets/muscles/core_upper.png',
  './assets/muscles/forearm.png',
  './assets/muscles/forearms.png',
  './assets/muscles/gluteus.png',
  './assets/muscles/hamstring.png',
  './assets/muscles/hands.png',
  './assets/muscles/latissimus.png',
  './assets/muscles/legs.png',
  './assets/muscles/neck.png',
  './assets/muscles/quadriceps.png',
  './assets/muscles/shoulders.png',
  './assets/muscles/shoulders_back.png',
  './assets/muscles/shoulders_front.png',
  './assets/muscles/triceps.png',
  './assets/foods/drinks/almond-milk.jpg',
  './assets/foods/dairy/butter.jpg',
  './assets/foods/dairy/cheddar-cheese.jpg',
  './assets/foods/drinks/coconut-milk.jpg',
  './assets/foods/dairy/cottage-cheese.jpg',
  './assets/foods/dairy/cream-cheese.jpg',
  './assets/foods/proteins/egg-whites.jpg',
  './assets/foods/proteins/eggs.jpg',
  './assets/foods/dairy/feta-cheese.jpg',
  './assets/foods/dairy/greek-yogurt.jpg',
  './assets/foods/dairy/mozzarella.jpg',
  './assets/foods/drinks/oat-milk.jpg',
  './assets/foods/dairy/parmesan.jpg',
  './assets/foods/dairy/ricotta.jpg',
  './assets/foods/dairy/skim-milk.jpg',
  './assets/foods/dairy/whole-milk.jpg',
  './assets/foods/fruits/apple.jpg',
  './assets/foods/fruits/avocado.jpg',
  './assets/foods/fruits/banana.jpg',
  './assets/foods/fruits/blueberries.jpg',
  './assets/foods/fruits/dates.jpg',
  './assets/foods/fruits/grapes.jpg',
  './assets/foods/fruits/mango.jpg',
  './assets/foods/fruits/orange.jpg',
  './assets/foods/fruits/pineapple.jpg',
  './assets/foods/fruits/strawberries.jpg',
  './assets/foods/fruits/watermelon.jpg',
  './assets/foods/grains/bagel.jpg',
  './assets/foods/grains/brown-rice.jpg',
  './assets/foods/grains/corn-tortilla.jpg',
  './assets/foods/grains/cornflakes.jpg',
  './assets/foods/grains/couscous.jpg',
  './assets/foods/grains/flour-tortilla.jpg',
  './assets/foods/grains/granola.jpg',
  './assets/foods/grains/oats.jpg',
  './assets/foods/grains/pasta.jpg',
  './assets/foods/grains/pita-bread.jpg',
  './assets/foods/grains/popcorn.jpg',
  './assets/foods/grains/quinoa.jpg',
  './assets/foods/grains/white-bread.jpg',
  './assets/foods/grains/white-rice.jpg',
  './assets/foods/grains/whole-wheat-bread.jpg',
  './assets/foods/legumes/black-beans.jpg',
  './assets/foods/legumes/chickpeas.jpg',
  './assets/foods/proteins/edamame.jpg',
  './assets/foods/vegetables/green-peas.jpg',
  './assets/foods/legumes/hummus.jpg',
  './assets/foods/legumes/kidney-beans.jpg',
  './assets/foods/legumes/lentils.jpg',
  './assets/foods/proteins/tofu.jpg',
  './assets/foods/proteins/beef-steak.jpg',
  './assets/foods/proteins/chicken-breast.jpg',
  './assets/foods/proteins/chicken-thigh.jpg',
  './assets/foods/proteins/ground-beef.jpg',
  './assets/foods/proteins/turkey-breast.jpg',
  './assets/foods/nuts-and-seeds/almond-butter.jpg',
  './assets/foods/nuts-and-seeds/almonds.jpg',
  './assets/foods/nuts-and-seeds/cashews.jpg',
  './assets/foods/nuts-and-seeds/chia-seeds.jpg',
  './assets/foods/nuts-and-seeds/flax-seeds.jpg',
  './assets/foods/nuts-and-seeds/macadamia-nuts.jpg',
  './assets/foods/nuts-and-seeds/peanut-butter.jpg',
  './assets/foods/nuts-and-seeds/peanuts.jpg',
  './assets/foods/nuts-and-seeds/pistachios.jpg',
  './assets/foods/nuts-and-seeds/pumpkin-seeds.jpg',
  './assets/foods/nuts-and-seeds/sesame-seeds.jpg',
  './assets/foods/nuts-and-seeds/sunflower-seeds.jpg',
  './assets/foods/nuts-and-seeds/tahini.jpg',
  './assets/foods/nuts-and-seeds/walnuts.jpg',
  './assets/foods/oils-and-condiments/coconut-oil.jpg',
  './assets/foods/oils-and-condiments/honey.jpg',
  './assets/foods/oils-and-condiments/maple-syrup.jpg',
  './assets/foods/oils-and-condiments/olive-oil.jpg',
  './assets/foods/oils-and-condiments/soy-sauce.jpg',
  './assets/foods/oils-and-condiments/tomato-sauce.jpg',
  './assets/foods/oils-and-condiments/ketchup.jpg',
  './assets/foods/oils-and-condiments/mustard.jpg',
  './assets/foods/oils-and-condiments/mayonnaise.jpg',
  './assets/foods/oils-and-condiments/pesto.jpg',
  './assets/foods/oils-and-condiments/bbq-sauce.jpg',
  './assets/foods/oils-and-condiments/hot-sauce.jpg',
  './assets/foods/oils-and-condiments/ranch-dressing.jpg',
  './assets/foods/oils-and-condiments/caesar-dressing.jpg',
  './assets/foods/oils-and-condiments/guacamole.jpg',
  './assets/foods/oils-and-condiments/tzatziki.jpg',
  './assets/foods/oils-and-condiments/tartar-sauce.jpg',
  './assets/foods/oils-and-condiments/teriyaki-sauce.jpg',
  './assets/foods/oils-and-condiments/fish-sauce.jpg',
  './assets/foods/oils-and-condiments/oyster-sauce.jpg',
  './assets/foods/oils-and-condiments/worcestershire.jpg',
  './assets/foods/oils-and-condiments/balsamic-vinegar.jpg',
  './assets/foods/oils-and-condiments/black-pepper.jpg',
  './assets/foods/oils-and-condiments/curry-paste.jpg',
  './assets/foods/oils-and-condiments/alfredo-sauce.jpg',
  './assets/foods/oils-and-condiments/condensed-milk.jpg',
  './assets/foods/oils-and-condiments/powdered-sugar.jpg',
  './assets/foods/saved-meals/Spicy-Salmon-Sweet-Potato.jpg',
  './assets/foods/saved-meals/teriyaki-chicken-rice-bowl.jpg',
  './assets/foods/saved-meals/pizza-slice.jpg',
  './assets/foods/saved-meals/burger.jpg',
  './assets/foods/proteins/salmon.jpg',
  './assets/foods/proteins/sardines.jpg',
  './assets/foods/proteins/tilapia.jpg',
  './assets/foods/proteins/tuna.jpg',
  './assets/foods/oils-and-condiments/dark-chocolate.jpg',
  './assets/foods/proteins/whey-protein.jpg',
  './assets/foods/vegetables/asparagus.jpg',
  './assets/foods/vegetables/bell-pepper.jpg',
  './assets/foods/vegetables/broccoli.jpg',
  './assets/foods/vegetables/cabbage.jpg',
  './assets/foods/vegetables/carrot.jpg',
  './assets/foods/vegetables/cauliflower.jpg',
  './assets/foods/vegetables/celery.jpg',
  './assets/foods/vegetables/corn.jpg',
  './assets/foods/vegetables/cucumber.jpg',
  './assets/foods/vegetables/eggplant.jpg',
  './assets/foods/vegetables/garlic.jpg',
  './assets/foods/vegetables/green-beans.jpg',
  './assets/foods/vegetables/kale.jpg',
  './assets/foods/vegetables/lettuce.jpg',
  './assets/foods/vegetables/mushrooms.jpg',
  './assets/foods/vegetables/onion.jpg',
  './assets/foods/vegetables/potato.jpg',
  './assets/foods/vegetables/spinach.jpg',
  './assets/foods/vegetables/sweet-potato.jpg',
  './assets/foods/vegetables/tomato.jpg',
  './assets/foods/vegetables/zucchini.jpg',
  './assets/exercises/abductors/Cable-hip-abduction.gif',
  './assets/exercises/abductors/HiP-ABDUCTION-MACHINE.gif',
  './assets/exercises/adductors/Cable-Hips-Adduction.gif',
  './assets/exercises/adductors/HIP-ADDUCTION-MACHINE.gif',
  './assets/exercises/back_lateral/Cable-Straight-Arm-Pulldown.gif',
  './assets/exercises/back_lateral/Close-Grip-Lat-Pulldown.gif',
  './assets/exercises/back_lateral/Dumbbell-Pullover.gif',
  './assets/exercises/back_lateral/Front-Pulldown.gif',
  './assets/exercises/back_lateral/Lat-Pulldown.gif',
  './assets/exercises/back_lateral/Seated-Row-Machine.gif',
  './assets/exercises/back_lateral/V-bar-Lat-Pulldown.gif',
  './assets/exercises/back_lateral/pull-ups.gif',
  './assets/exercises/back_lower/hyperextension.gif',
  './assets/exercises/back_upper/Barbell-Bent-Over-Row.gif',
  './assets/exercises/back_upper/Dumbbell-Row.gif',
  './assets/exercises/back_upper/Dumbbell-Shrug.gif',
  './assets/exercises/back_upper/One-arm-Cable-Row.gif',
  './assets/exercises/back_upper/Seated-Cable-Rope-Row.gif',
  './assets/exercises/back_upper/Seated-Cable-Row.gif',
  './assets/exercises/back_upper/T-Bar-Row.gif',
  './assets/exercises/biceps/Barbell-Curl.gif',
  './assets/exercises/biceps/Dumbbell-Curl.gif',
  './assets/exercises/biceps/Hammer-Curl.gif',
  './assets/exercises/biceps/Lever-Preacher-Curl.gif',
  './assets/exercises/biceps/One-Arm-Cable-Curl.gif',
  './assets/exercises/biceps/Seated-Incline-Dumbbell-Curl.gif',
  './assets/exercises/biceps/Z-Bar-Preacher-Curl.gif',
  './assets/exercises/biceps/cable-single-arm-hammer-curl.gif',
  './assets/exercises/calves/Dumbbell-Calf-Raise.gif',
  './assets/exercises/calves/Leg-Press-Calf-Raise.gif',
  './assets/exercises/calves/Lever-Seated-Calf-Raise.gif',
  './assets/exercises/calves/Standing-Calf-Raise.gif',
  './assets/exercises/chest/Barbell-Bench-Press.gif',
  './assets/exercises/chest/Chest-Dips.gif',
  './assets/exercises/chest/Dumbbell-Fly.gif',
  './assets/exercises/chest/Dumbbell-Press-1.gif',
  './assets/exercises/chest/High-Cable-Crossover.gif',
  './assets/exercises/chest/Incline-Barbell-Bench-Press.gif',
  './assets/exercises/chest/Incline-Chest-Fly-Machine.gif',
  './assets/exercises/chest/Pec-Deck-Fly.gif',
  './assets/exercises/core/Ab-Coaster-Machine.gif',
  './assets/exercises/core/Bicycle-Crunch.gif',
  './assets/exercises/core/Captains-Chair-Leg-Raise.gif',
  './assets/exercises/core/Cross-Crunch.gif',
  './assets/exercises/core/Crunch.gif',
  './assets/exercises/core/Decline-Sit-up.gif',
  './assets/exercises/core/Dumbbell-Side-Bend.gif',
  './assets/exercises/core/Heel-Touch.gif',
  './assets/exercises/core/Kneeling-Cable-Crunch.gif',
  './assets/exercises/core/Lying-Leg-Raise.gif',
  './assets/exercises/core/Lying-Scissor-Kick.gif',
  './assets/exercises/core/Mountain-climber.gif',
  './assets/exercises/core/Seated-Bench-Leg-Pull-in.gif',
  './assets/exercises/core/Single-Leg-Dumbbell-Side-Bridge.gif',
  './assets/exercises/core/Standing-Cable-Crunch.gif',
  './assets/exercises/forearms/Dumbbell-Wrist-Curl.gif',
  './assets/exercises/forearms/Reverse-Grip-EZ-Bar-Curl.gif',
  './assets/exercises/forearms/dumbbell-reverse-curl.gif',
  './assets/exercises/forearms/seated-barbell-finger-curl.gif',
  './assets/exercises/forearms/wrist-roller.gif',
  './assets/exercises/glutes/Barbell-Hip-Thrust.gif',
  './assets/exercises/glutes/Barbell-Sumo-Deadlift.gif',
  './assets/exercises/glutes/Hip-Thrust-Machine.gif',
  './assets/exercises/glutes/Kettlebell-Swings.gif',
  './assets/exercises/glutes/Lever-Standing-Rear-Kick.gif',
  './assets/exercises/glutes/Smith-Machine-Reverse-Kickback.gif',
  './assets/exercises/hamstrings/Barbell-Deadlift.gif',
  './assets/exercises/hamstrings/Barbell-Romanian-Deadlift.gif',
  './assets/exercises/hamstrings/Leg-Curl.gif',
  './assets/exercises/hamstrings/Seated-Leg-Curl.gif',
  './assets/exercises/quads/Dumbbell-Bulgarian-Split-Squat.gif',
  './assets/exercises/quads/Dumbbell-Goblet-Squat.gif',
  './assets/exercises/quads/LEG-EXTENSION.gif',
  './assets/exercises/quads/Leg-Press.gif',
  './assets/exercises/quads/Reverse-Lunge-Knee (1).gif',
  './assets/exercises/quads/Sled-Hack-Squat.gif',
  './assets/exercises/quads/dumbbell-lunges.gif',
  './assets/exercises/quads/squat.gif',
  './assets/exercises/shoulders/Alternating-Dumbbell-Front-Raise.gif',
  './assets/exercises/shoulders/Arnold-Press.gif',
  './assets/exercises/shoulders/Barbell-Shoulder-Press.gif',
  './assets/exercises/shoulders/Barbell-Upright-Row.gif',
  './assets/exercises/shoulders/Cable-Front-Raise.gif',
  './assets/exercises/shoulders/Cable-Lateral-Raise.gif',
  './assets/exercises/shoulders/Dumbbell-Front-Raise.gif',
  './assets/exercises/shoulders/Dumbbell-Lateral-Raise.gif',
  './assets/exercises/shoulders/Dumbbell-Shoulder-Press.gif',
  './assets/exercises/shoulders/Dumbbell-Upright-Row.gif',
  './assets/exercises/shoulders/Face-Pull.gif',
  './assets/exercises/shoulders/Rear-Delt-Fly-On-Machine.gif',
  './assets/exercises/shoulders/Standing-Dumbbell-Overhead-Press.gif',
  './assets/exercises/shoulders/cable-rear-delt-fly.gif',
  './assets/exercises/triceps/Cable-Rope-Overhead-Triceps-Extension.gif',
  './assets/exercises/triceps/Dumbbell-Incline-Two-Arm-Extension.gif',
  './assets/exercises/triceps/Dumbbell-Kickback.gif',
  './assets/exercises/triceps/Lever-Overhand-Triceps-Dip.gif',
  './assets/exercises/triceps/Seated-One-Arm-Dumbbell-Triceps-Extension.gif',
  './assets/exercises/triceps/Triceps-Dips-on-Floor.gif',
  './assets/exercises/triceps/Triceps-Dips.gif',
  './assets/exercises/triceps/tríceps-pulley-rope.gif',
];

// Pre-cache core files on install, then cache assets in the background.
// Assets are cached individually so a single 404 doesn't abort the rest.
self.addEventListener('install', e => {
  self.skipWaiting();
  e.waitUntil(
    caches.open(CACHE).then(c => c.addAll(CORE)).then(() =>
      caches.open(CACHE).then(c =>
        Promise.all(ASSETS.map(url =>
          c.add(url).catch(() => { /* skip missing/failed asset */ })
        ))
      )
    )
  );
});

// Take control immediately & clean old caches
self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
    ).then(() => clients.claim())
  );
});

// Cache-first for static assets (images, fonts) — they never change without
// a deploy, so serving from cache eliminates the network round-trip that
// was causing thumbnails to paint a few seconds late.
// Network-first for everything else so code/data stays fresh.
const ASSET_RE = /\.(?:gif|png|jpe?g|webp|svg|woff2?|ttf|otf)$/i;

// Hosts whose responses must never be cached (auth tokens, Firestore, Worker proxy).
// Their responses are user-specific and short-lived; caching them risks serving
// stale auth state or another user's data.
const NO_CACHE_HOST_RE = /(^|\.)(googleapis\.com|gstatic\.com|firebaseio\.com|firebase\.com|workers\.dev|openfoodfacts\.org)$/i;

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET' || !e.request.url.startsWith('http')) return;

  const url = new URL(e.request.url);
  if (NO_CACHE_HOST_RE.test(url.hostname)) return;

  if (ASSET_RE.test(url.pathname)) {
    e.respondWith(
      caches.match(e.request).then(hit => hit || fetch(e.request).then(res => {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
        return res;
      }))
    );
    return;
  }

  e.respondWith(
    fetch(e.request)
      .then(res => {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
        return res;
      })
      .catch(() => caches.match(e.request))
  );
});
